import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import NavBar from './components/NavBar';
import Footer from './components/Footer';
import { AuthProvider } from './components/AuthContext';
import { CartProvider } from './components/CartContext';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'RS Shop',
  description: 'Generated by create next app',
};

console.log(
  'Rendering on',
  typeof window === 'undefined' ? 'Server' : 'Client'
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray88`}
      >
        <AuthProvider>
          <CartProvider>
            <header>
              <NavBar />
            </header>
            {children}
            <footer>
              <Footer />
            </footer>
          </CartProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
